### ISSUE TITLE
I got Nan Yen

### ISSUE THREAD

**Issue by suguru03** [1000ch/amazon-payment-history#1]
I can't see my payment histories. 
I guess it is because I haven't bought anything this year. 
Could you look into it?
<img width="160" alt="screen shot 2016-09-01 at 1 15 22 am" src="https://cloud.githubusercontent.com/assets/8013633/18160328/c2c4bbf6-6fe1-11e6-9a19-19a682378b9c.png">

**Comment by 1000ch** [comment]
@suguru03 Thank you, I'll fix it soon.
BTW, did (can) you execute it on `amazon.co.jp` ? (I guess you are in Canada)

**Comment by suguru03** [comment]
Thanks for reply!
Yes, I did. The extension redirects the url.
I tried it on incognito window but I got same result.

**Comment by 1000ch** [comment]
> I tried it on incognito window but I got same result.

This extension does not expect to be executed on other region 😭 
PR is always welcome to correspond!

**Comment by suguru03** [comment]
Sure! I'll try to fix it. 😄

**Comment by 1000ch** [comment]
@suguru03 Published.

**Comment by suguru03** [comment]
It works! Thanks! :)
